version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_sever
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
       - mssql_data:/var/opt/mssql
       - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - mssql_network

networks:
  mssql_network:

volumes:
  mssql_data: